PO:
  0:
    Q: [0.0025]
    R: [1.0, 1.0, 1.0]
    N: 16
    M: 8
  1:
    Q: [0.0025]
    R: [1.0, 1.0, 1.0]
    N: 16
    M: 8
  2:
    Q: [0.1, 0.1, 0.1]
    R: [5.0, 5.0, 5.0]
    N: 16
    M: 8
  3:
    Q: [0.0025]
    R: [1.0, 1.0, 1.0]
    N: 20
    M: 10
  4:
    Q: [1]
    R: [5.0, 5.0, 5.0]
    N: 18
    M: 8
  5:
    Q: [0.001]
    R: [2.0, 2.0, 2.0]
    N: 20
    M: 10
  6:
    Q: [0.01, 0.1]
    R: [4.0, 2.0, 2.0]
    N: 10
    M: 5
  7:
    Q: [2]
    R: [20.0, 10.0, 10.0]
    N: 10
    M: 5